version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - /databases/db:/var/lib/postgresql/data
